name: CI/CD Saraha-app
on:
  push:
    branches:
      - main
jobs:
  build:
    uses: ./.github/workflows/build.yml@main
  
  test:
    needs: build
    uses: ./.github/workflows/test.yml@main

  docker-push:
    needs: test
    uses: ./.github/workflows/docker-push.yml@main