name: RUN test

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v5.0.0
        
      - name: setup node.js
        uses: actions/setup-node@v5.0.0
        with:
          node-version: "18"
      - name: run test
        run: npm test